# Generated by Django 2.1.3 on 2018-12-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_requisition_no', models.CharField(max_length=150)),
                ('issued_or_not', models.CharField(max_length=15)),
                ('issued_date', models.DateTimeField()),
                ('issuer_email_id', models.CharField(max_length=150)),
                ('issued_to', models.ForeignKey(blank=True, db_column='issued_to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='barcodeapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('gate_pass_no', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('value', models.IntegerField(null=True)),
                ('barcode', models.CharField(max_length=15, null=True)),
                ('unity_of_measurement', models.CharField(default='NOS', max_length=255)),
                ('lrd', models.DateField(blank=True, null=True)),
                ('lid', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShelfSticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Godown')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Rack')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Shelf')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existing_quantuty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Product')),
                ('storage_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Shelf')),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Product'),
        ),
        migrations.AddField(
            model_name='exit',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='barcodeapp.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='shelfsticker',
            unique_together={('godown', 'rack', 'shelf')},
        ),
    ]
