# Generated by Django 2.1.3 on 2018-11-20 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('value', models.IntegerField(null=True)),
                ('barcode', models.CharField(max_length=15, null=True)),
                ('expiry_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchaserequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='barcodeapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Productsticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchaserequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_or_revenue', models.CharField(max_length=255)),
                ('indent_no', models.IntegerField(blank=True, null=True)),
                ('indentor_name', models.CharField(max_length=255)),
                ('indentor_designation', models.CharField(max_length=255)),
                ('purpose_of_procurement', models.CharField(max_length=255)),
                ('nature_of_indent', models.CharField(max_length=255)),
                ('section_code', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('fullfilled_or_not', models.IntegerField()),
                ('fullfilled_date', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(db_column='department', on_delete=django.db.models.deletion.DO_NOTHING, to='barcodeapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('godown', models.ForeignKey(db_column='Godown', on_delete=django.db.models.deletion.DO_NOTHING, to='barcodeapp.Godown')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('rack', models.ForeignKey(db_column='rack', on_delete=django.db.models.deletion.DO_NOTHING, to='barcodeapp.Rack')),
            ],
        ),
        migrations.CreateModel(
            name='Shelfsticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Godown')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Rack')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Shelf')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unity_of_measurement', models.CharField(default='NOS', max_length=255)),
                ('lrd', models.DateField(blank=True, null=True)),
                ('lid', models.DateField(blank=True, null=True)),
                ('issued_or_not', models.CharField(max_length=15)),
                ('issued_date', models.DateTimeField()),
                ('issued_to', models.ForeignKey(blank=True, db_column='issued_to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='barcodeapp.Department')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='barcodeapp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productpurchaserequisition',
            name='purchaserequisition',
            field=models.ForeignKey(db_column='purchaserequisition', on_delete=django.db.models.deletion.DO_NOTHING, to='barcodeapp.Purchaserequisition'),
        ),
    ]
