# Generated by Django 2.1.3 on 2018-12-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0002_auto_20181210_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exit',
            old_name='purchase_order_no',
            new_name='product_requisition_no',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='lid',
            new_name='last_issued_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='lrd',
            new_name='last_received_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
    ]
