# Generated by Django 2.1.3 on 2018-12-17 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0002_auto_20181214_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='issued_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_issued_date',
            field=models.DateField(default=datetime.date(2020, 11, 16)),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_received_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
