# Generated by Django 2.1.3 on 2018-12-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0003_auto_20181208_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsticker',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Product', unique=True),
        ),
    ]
