# Generated by Django 2.1.3 on 2018-11-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0003_auto_20181120_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='godown',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='rack',
        ),
        migrations.AddField(
            model_name='shelfsticker',
            name='barcode',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
