# Generated by Django 2.1.3 on 2018-12-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0003_auto_20181217_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
