# Generated by Django 2.1.3 on 2018-12-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0004_auto_20181217_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unity_of_measurement',
            field=models.CharField(choices=[('NUMBERS', 'NOS'), ('DOZEN', 'DZ'), ('PADS', 'PD')], max_length=255),
        ),
    ]
