# Generated by Django 2.1.3 on 2018-12-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0004_auto_20181208_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsticker',
            name='purchase_order_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.PurchaseOrder'),
        ),
        migrations.AlterField(
            model_name='productsticker',
            name='product_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='productsticker',
            unique_together={('product_code', 'purchase_order_no')},
        ),
    ]
