# Generated by Django 2.1.3 on 2018-11-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0004_auto_20181120_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfsticker',
            name='barcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
