# Generated by Django 2.1.3 on 2018-12-08 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0005_auto_20181208_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsticker',
            name='product_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Product', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='productsticker',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productsticker',
            name='purchase_order_no',
        ),
    ]
