# Generated by Django 2.1.3 on 2018-12-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0005_auto_20181217_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsticker',
            name='product_code',
        ),
        migrations.AddField(
            model_name='productsticker',
            name='product_code',
            field=models.ManyToManyField(to='barcodeapp.Product'),
        ),
    ]
