# Generated by Django 2.1.3 on 2018-11-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0005_auto_20181120_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfsticker',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
