# Generated by Django 2.1.3 on 2018-12-17 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0007_auto_20181217_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exit',
            name='product',
        ),
        migrations.AddField(
            model_name='exit',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Product'),
            preserve_default=False,
        ),
    ]
