# Generated by Django 2.1.3 on 2019-01-21 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0008_auto_20181217_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='godown',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rack',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shelf',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='last_issued_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 21), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unity_of_measurement',
            field=models.CharField(choices=[('NOS', 'NOS'), ('DOZEN', 'DZ'), ('PADS', 'PD'), ('SET', 'SET'), ('LEN', 'LEN'), ('KGS', 'KGS'), ('LIT', 'LIT'), ('BOT', 'BOT'), ('SQM', 'SQM'), ('PKT', 'PKT'), ('MTR', 'MTR'), ('BUN', 'BUN')], max_length=255),
        ),
    ]
