# Generated by Django 2.1.3 on 2018-11-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0008_auto_20181123_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='lid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='lrd',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unity_of_measurement',
        ),
    ]
