# Generated by Django 2.1.3 on 2019-01-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0009_auto_20190121_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='godown',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
