# Generated by Django 2.1.3 on 2018-11-23 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0009_auto_20181123_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_requisition_no', models.CharField(max_length=150)),
                ('issued_or_not', models.CharField(max_length=15)),
                ('issued_date', models.DateTimeField()),
                ('issuer_email_id', models.CharField(max_length=150)),
                ('issued_to', models.ForeignKey(blank=True, db_column='issued_to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='barcodeapp.Department')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='barcodeapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('gate_pass_no', models.CharField(max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='productpurchaserequisition',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productpurchaserequisition',
            name='purchaserequisition',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='department',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issued_or_not',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issued_to',
        ),
        migrations.AddField(
            model_name='stock',
            name='existing_quantuty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='storage_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Shelf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelfsticker',
            name='shelf',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Product'),
        ),
        migrations.DeleteModel(
            name='ProductPurchaserequisition',
        ),
        migrations.DeleteModel(
            name='Purchaserequisition',
        ),
    ]
