# Generated by Django 2.0 on 2019-02-01 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0010_auto_20190121_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInscan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='godown',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_issued_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 1), null=True),
        ),
        migrations.AddField(
            model_name='productinscan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Product'),
        ),
    ]
