# Generated by Django 2.0 on 2019-02-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0011_auto_20190201_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinscan',
            name='product',
            field=models.CharField(max_length=150),
        ),
    ]
