# Generated by Django 2.1.3 on 2018-12-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0012_auto_20181203_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_order_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.PurchaseOrder'),
            preserve_default=False,
        ),
    ]
