# Generated by Django 2.1.3 on 2018-12-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0013_product_purchase_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='godown',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Godown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelf',
            name='rack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barcodeapp.Rack'),
            preserve_default=False,
        ),
    ]
