# Generated by Django 2.1.3 on 2018-12-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeapp', '0014_auto_20181206_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelfsticker',
            name='godown',
        ),
    ]
